### ISSUE TITLE
[BUG] Does not work on older versions of Java

### ISSUE THREAD

**Issue by BorgzPony** [ConnorDY/OSRS-Environment-Exporter#105]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: AppKt has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

soo what Version of Java do i need to have downloaded to uses this seen i not updated java in some time as i run Older Builds of Minecraft

so im mainly asking seen its not listed anywhere on here and google was no help asking what Java runtime version is 55

**Comment by ConnorDY** [comment]
In the future, please use the provided bug report template and provide a descriptive title.

I'm away from my computer right now, but later I can check the minimum version that is required and let you know.

**Comment by ScoreUnder** [comment]
Java 11 is the minimum version we target with this project, and I am testing on Java 18.

You can see here for a list of class versions compared to java versions: https://javaalmanac.io/bytecode/versions/
