### ISSUE TITLE
[BUG] Unable to load various new chunks with "Change Region". Out of range.

### ISSUE THREAD

**Issue by LengaJenga** [ConnorDY/OSRS-Environment-Exporter#134]
- [x] I am using the latest version of the exporter

## Bug description

Regions out of range:
- 15700
- 15698
- 15696
- 15955
- 15954
- 15953

## Steps to reproduce

1. World -> Change Region
2. Input any of the listed regions above
3. Radius 1
4. "Region ID(s) must be between 4647 and 15522"

## The current behavior

Region chooser is unable to load these regions as they are out of range to select.

## The expected behavior

Region loads as normal.

## EXTRA NOTE

Load Custom Grid **_IS_** able to load the new chunks with this configuration:
![image](https://user-images.githubusercontent.com/19176925/186960743-579cc413-20ab-46f2-a5e9-140552ef965e.png)

**Comment by ScoreUnder** [comment]
Fixed in #136
