### ISSUE TITLE
[BUG] Unable to open

### ISSUE THREAD

**Issue by Nguyen-Gmod** [ConnorDY/OSRS-Environment-Exporter#148]
- [x] I am using the latest version of the exporter

## Bug description

When trying to open the program I get JNI error, when trying to open it from CMD i get "Unable to access Jar file"

## Steps to reproduce

1. Try to open program

**Comment by ScoreUnder** [comment]
Hi, what happens when you run the `run.bat` provided in the package? (If you don't have that, you can get one from the [release zip](https://github.com/ConnorDY/OSRS-Environment-Exporter/releases/download/2.2.0/osrs-environment-exporter-2.2.0.zip)

**Comment by Nguyen-Gmod** [comment]
it does nothing, does not open anything

**Comment by ScoreUnder** [comment]
Thanks for checking. We only support Java 11 and above, so you will have to update. You can get newer versions from Microsoft: https://docs.microsoft.com/en-gb/java/openjdk/download

**Comment by ScoreUnder** [comment]
Going to assume it worked; if it is still broken in more recent Java versions please reopen

**Comment by ninapetr** [comment]
Experiencing the same issue both with java 19 and 17.
