### ISSUE TITLE
OSRS-Environment-Exporter violates RuneLite license

### ISSUE THREAD

**Issue by Adam-** [ConnorDY/OSRS-Environment-Exporter#153]
First off, this is a nice project and I appreciate the work you have put into it. I see that it uses both the renderer from RuneLite and also some of the cache tooling. While you are allowed to release this under GPL-3, you must also retain the existing BSD-2 license and also release it under that, it is not okay to de-license the code as you are doing. BSD-2 states that the license & header must be included in any redistribution of the work, with or without modification.

I see that some effort has gone into preserving the licenses on some of the files, particularly the shaders, which I appreciate. There are several other files missed. For example, SpirteLoader, which has *11 identical comments* to RL, including this 3-line one:
![image](https://user-images.githubusercontent.com/309739/192284039-ac80ff49-6ea5-4dfa-8405-b6896fa751dd.png)
which makes it obviously a modified work.

Most of your renderer seems to be modified RL code too, it even has a *comment* about the *plugin* from RL which obviously is no longer applicable to it 
![image](https://user-images.githubusercontent.com/309739/192284340-50f84612-184c-4c64-9621-8e610c0589b8.png)

Note that these are just random samples, I think almost everything in `cache` was just RL with a java to kotlin converter run on it.

I ask that you reinstate the original license header to each file that is derived from a file in RuneLite.

Thanks,
Adam

**Comment by ScoreUnder** [comment]
Hi, apologies, it was not our intent to remove the license from any of the code present in here. The project had quite a rocky start involving code and contributors both going missing which has made a lot of the earlier code a lot less traceable via any sensible git history, and while we've done what we can to put things back together, evidently there are parts we have missed.
Once I'm back from work I will look into which files derive code from runelite and put the correct license notice onto each one.
+ paging @ConnorDY
