### ISSUE TITLE
[BUG] Error loading "Jaldraocht Pyramid level 4 (Desert Treasure) [12945]"

### ISSUE THREAD

**Issue by LengaJenga** [ConnorDY/OSRS-Environment-Exporter#172]
- [x] I am using the latest version of the exporter

## Bug description
When loading region ID 12945, it looks as if a variety of the height layers/the models do not load at all, but the surrounding regions do.

This is the error that is spat out when loading the region.
`13:43:38.335 [Thread-12] WARN  models.scene.SceneRegionBuilder - Could not find location (entity) data for region 12945`

## Steps to reproduce

1. Click "World"
2. Click "Location Search"
3. Type in "jaldraocht"
4. Select "Jaldraocht Pyramid level 4 (Desert Treasure) [12945]"
5. Keep radius to 1
6. Look at the console output

## The current behavior
Screenshot of the current issue
![image](https://user-images.githubusercontent.com/19176925/216682546-91cd2385-bef1-4676-a31b-f86b86a9ed49.png)

## The expected behavior
![image](https://user-images.githubusercontent.com/19176925/216682622-bfab00ae-ff87-4044-928b-ec56fba891e0.png)

**Comment by ConnorDY** [comment]
Fixed in #174.
