### ISSUE TITLE
Enhancement: Change materials that use image textures to have blend mode "alpha clip" by default

### ISSUE THREAD

**Issue by trillionosrs** [ConnorDY/OSRS-Environment-Exporter#24]
![image](https://user-images.githubusercontent.com/109128030/178902965-4a0bf241-4abf-47d6-9a1a-f021d65a83cd.png)

![image](https://user-images.githubusercontent.com/109128030/178903084-3d874aeb-a0a8-4833-9ac7-1dcb41aac957.png)

![image](https://user-images.githubusercontent.com/109128030/178903440-5c283408-efb1-40a1-b8d7-9c69f0761152.png)

### **Steps to reproduce**
-Click "World" dropdown and select "Change Region"
-Load "Region ID" 12850 with "Radius" 1
-Click "Export" button
-Import colors.ply and materials.obj in Blender
-Observe textures that are imported from materials.obj that require transparency, are black where it should be transparent. 
-Select appropriate material
-Open "Shading" tab at top of Blender application
-Click and drag to connect the "Alpha channel" of the .png to the other alpha channel as seen in image 2 above. 
-Change blending mode of material to "Alpha Clip" as seen in image 3

**Comment by ConnorDY** [comment]
Fixed in #28.
