### ISSUE TITLE
[BUG] Lava previews and exports incorrectly at region '15263' and '15262'

### ISSUE THREAD

**Issue by LengaJenga** [ConnorDY/OSRS-Environment-Exporter#53]
![image](https://user-images.githubusercontent.com/19176925/181935696-1fd33bb2-235c-46f4-8751-d1d39a5ff58a.png)

Version: 2.0
OS: Windows 10
GLTF was viewed with [this](https://gltf-viewer.donmccurdy.com/)
Region loaded: 15262 at a radius of 2

**Comment by ConnorDY** [comment]
Do you know what area of OSRS this is supposed to be?

**Comment by LengaJenga** [comment]
> Do you know what area of OSRS this is supposed to be?

Volcanic Mine

**Comment by ConnorDY** [comment]
This will be included in the next update/release:
![image](https://user-images.githubusercontent.com/945062/184282988-312455c7-64a1-457c-a8e1-f7305c6e72e4.png)
