### ISSUE TITLE
Menu unresponsive.

### ISSUE THREAD

**Issue by W83official** [ConnorDY/OSRS-Environment-Exporter#54]
OSRS-Enviroment-exporet-2.0..0
Launching version: 22-07-20-rev206.tar.gz

once booted up. (after downloading all files from the GitHub) the menu does not respond. 
Export button works fine. (Submitted video in Trillion Discord) 

What does **not** work:

- World
- Edit
- Help

what does work:

- Export
- Z-layer z0/z1/z2/z3

Fps remains unknown as I am unable to import any world ID numbers.

**Comment by LengaJenga** [comment]
Example video of it not working:
https://user-images.githubusercontent.com/19176925/181936148-8b3a1c2e-813e-4a3a-ad46-df576cb6b37c.mov

**Comment by ConnorDY** [comment]
User said he was on Windows 11.

I've updated the release to include a ZIP file with the following additional files:
- `run.bat` (for Windows)
- `run` (for Mac and Linux)

Using the `run.bat` launcher scripts appears to resolve the issue the user was experiencing.


`osrs-environment-exporter-2.0.0.zip` can be downloaded here (at the bottom):
https://github.com/ConnorDY/OSRS-Environment-Exporter/releases/tag/2.0.0
