### ISSUE TITLE
Can't click on tabs, only export and layers work.

### ISSUE THREAD

**Issue by HerbRSPS** [ConnorDY/OSRS-Environment-Exporter#58]
https://i.imgur.com/UbLTQwn.gif

**Comment by ConnorDY** [comment]
Hello! Please use the provided `run.bat` file if you are on Windows.

If you do not have the run script, please redownload `osrs-environment-exporter-2.0.0.zip` from here:
https://github.com/ConnorDY/OSRS-Environment-Exporter/releases/tag/2.0.0

**Comment by ConnorDY** [comment]
This is a duplicate of #54.
