### ISSUE TITLE
[BUG] Giants' Foundry missing from location search

### ISSUE THREAD

**Issue by LengaJenga** [ConnorDY/OSRS-Environment-Exporter#87]
- [x] I am using the latest version of the exporter

## Bug description

The location for the Giants' Foundry minigame is missing from the location search.
The region ID for the Giants' Foundry is `13491`

## Steps to reproduce

1. World -> Location Search
2. Type "Foundry"

## The current behavior
![image](https://user-images.githubusercontent.com/19176925/184507389-d829774e-95f1-4db6-9c9c-a268104ccd03.png)

## The expected behavior
![image](https://user-images.githubusercontent.com/19176925/184507416-14992f49-155f-4a41-85ca-a72a47557352.png)

**Comment by ConnorDY** [comment]
Fixed in PR #88.
