### ISSUE TITLE
[BUG] Exported models aren't always rotated properly

### ISSUE THREAD

**Issue by ScoreUnder** [ConnorDY/OSRS-Environment-Exporter#90]
- [x] I am using the latest version of the exporter

## Bug description

Some models have yet another way of storing rotation information, that is, they get an "orientation type" which gets processed at shader time. But that also means it doesn't get exported.

See https://github.com/ConnorDY/OSRS-Environment-Exporter/pull/86/commits/4a9e01796129b02e219da9de735a703caf1fe3b4 for a nudge on how to implement it

We should probably bake that in at object load time tbh.

## Steps to reproduce

1. Export the default scene
2. Compare the standing armour statues in the corners in blender vs the exporter preview

## The current behavior

The exporter preview shows it correctly at a 45 degree angle, but the exported model does not.

![2022-08-14-082357455739286](https://user-images.githubusercontent.com/1123686/184527035-d1393482-6fc3-4e0c-9469-17397fa7fdf4.png)

## The expected behavior

As above, the exported model should also have these things rotated.

![2022-08-14-082105352426986](https://user-images.githubusercontent.com/1123686/184527034-5ff1a263-8f16-44ae-9bab-e8fe50ad7cd4.png)

**Comment by ConnorDY** [comment]
**Potential temporary fix:** Make sure each object exports as its own mesh to make them easier to move?

**Comment by ScoreUnder** [comment]
The data flow for this in the normal renderer(s) is:

* LocationsLoader loads in a list of entities from the cache
* SceneRegionBuilder processes those entities, and performs a rotation based on `loc.orientation` - this is not what the ticket is about, it's a separate rotation performed earlier and baked into the model vertices
* SceneRegionBuilder will assign `OrientationType.DIAGONAL` to some models
* The model exposes this orientation in the bottom 11 bits of its `renderFlags` field
* `renderFlags` gets passed to the `flags` field of the corresponding `ComputeObj` (see `AbstractPriorityRenderer#positionRenderable`)
* GLSL path:
  * the `computeObj` is written out as an array into a buffer (`GLSLPriorityRenderer#positionRenderable`)
  * the buffer is transferred to the GPU (`GLSLPriorityRenderer#finishPositioning`) and bound to a variable in the shader (`GLSLPriorityRenderer#produceVertices`)
  * the shaders rotate according to the bottom 11 bits of the flags (`priority_renderer.glsl`, `get_face`)
* CPU path:
  * the bottom 11 bits of `computeObj.flags` is taken and looked up in the precomputed fixed-point sine/cosine tables
* a standard rotation on the Y axis is performed, except since the sin/cos are fixed point values with the point fixed at 16 bits, there needs to be a right shift of 16 bits on the resulting values to turn them back into integers

The vertexes are then written out to wherever they need to go to keep the render pipeline flowing. The fact that the rotation happens so late in the pipeline is a little concerning to me, so either you could emulate this in `SceneExporter`, or you could make the rotation happen earlier (see `ModelDefinition.rotate`)

Note that the angles are all in the range `0 ≤ angle < 2048` which corresponds to the real world angles of `0 ≤ angle < 2π`
